### ISSUE TITLE
Custom dataset

### ISSUE THREAD

**Issue by xubaixinxbx** [limacv/NeUVF#3]
Hi, is there any way to get the uv_gt for a custom dataset? Unfortunately, PRNet failed since it ran on the old machine and version, and has published 5 years ago.

**Comment by limacv** [comment]
It's totally possible to get uv_gt in other ways. Any face tracking algorithm will do the trick. And the tracking doesn't need to be perfect (the PRNet isn't very accurate neither). What to expect is a set of tracked vertices and a pre-defined uv coordinates

**Comment by xubaixinxbx** [comment]
Hi,
Thanks for your advice! I trained on facescape, and unfortunately, I got an out-of-expectation result like this. It seems uv cropped along the human frontal face, rather than behind, Do you have advice on this? Thanks for your help!
![image](https://github.com/limacv/NeUVF/assets/113180125/2a4605d7-5609-47b5-a70d-5d17cf1985a1)

**Comment by limacv** [comment]
Do you have a visualization of the uv_gt. It's helpful to see where the supervision points land at the texture space

**Comment by xubaixinxbx** [comment]
Thanks for your advice! Its true that the ground truth of UV matters

**Comment by xubaixinxbx** [comment]
Thanks for authors reponse
